### ISSUE TITLE
"checking whether printf survives out-of-memory conditions" hangs

### ISSUE THREAD

**Issue by ant1** [seanbruno/qemu-bsd-user#92]
See https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=224740

**Comment by kevans91** [comment]
For later reference, stack trace:

```
#0  _umtx_op_err () at /usr/src/lib/libthr/arch/amd64/amd64/_umtx_op_err.S:37
#1  0x0000000060169b20 in _thr_umtx_timedwait_uint (mtx=0x624f3d60 <default_wake_addr+8>, id=<optimized out>, 
    clockid=<optimized out>, abstime=<optimized out>, shared=<optimized out>) at /usr/src/lib/libthr/thread/thr_umtx.c:236
#2  0x00000000601735cb in cond_wait_user (cvp=<optimized out>, mp=<optimized out>, abstime=0x0, cancel=1)
    at /usr/src/lib/libthr/thread/thr_cond.c:320
#3  cond_wait_common (cond=<optimized out>, mutex=<optimized out>, abstime=0x0, cancel=1) at /usr/src/lib/libthr/thread/thr_cond.c:380
#4  0x00000000600da585 in qemu_cond_wait_impl (cond=0x624e85b0 <exclusive_cond>, mutex=0x624e85a0 <qemu_cpu_list_lock>, 
    file=0x60282808 "cpus-common.c", line=204) at util/qemu-thread-posix.c:164
#5  0x000000006007eac9 in start_exclusive () at cpus-common.c:204
#6  0x000000006002cb52 in force_sig (target_sig=6)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/bsd-user/signal.c:345
#7  0x000000006002cdad in queue_signal (env=0x8605a7098, sig=6, info=0x7ffffffe8ac8)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/bsd-user/signal.c:463
#8  0x000000006002d17f in host_signal_handler (host_signum=<optimized out>, info=0x7ffffffe92f0, puc=0x7ffffffe8f80)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/bsd-user/signal.c:492
#9  0x000000006016b08e in handle_signal (actp=0x7ffffffe8f08, sig=6, info=0x7ffffffe92f0, ucp=0x7ffffffe8f80)
    at /usr/src/lib/libthr/thread/thr_sig.c:246
#10 0x000000006016a648 in thr_sighandler (sig=6, info=0x7ffffffe92f0, _ucp=0x7ffffffe8f80) at /usr/src/lib/libthr/thread/thr_sig.c:191
#11 <signal handler called>
#12 thr_kill () at thr_kill.S:4
#13 0x000000006025ec9f in __raise (s=6) at /usr/src/lib/libc/gen/raise.c:52
#14 0x00000000601dc079 in abort () at /usr/src/lib/libc/stdlib/abort.c:67
#15 0x00000000600fb63a in mem_error ()
#16 0x00000000600fa64f in slab_allocator_alloc_chunk ()
#17 0x00000000600fa130 in g_slice_alloc ()
#18 0x0000000060109604 in g_tree_insert_internal ()
#19 0x0000000060023b2b in tb_gen_code (cpu=<optimized out>, pc=<optimized out>, cs_base=0, flags=524416, cflags=1616597720)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/accel/tcg/translate-all.c:1398
#20 0x0000000060022a2a in tb_find (cpu=0x86059ee80, last_tb=0x0, tb_exit=0, cf_mask=0)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/accel/tcg/cpu-exec.c:404
#21 0x00000000600226d9 in cpu_exec (cpu=0x86059ee80)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/accel/tcg/cpu-exec.c:731
#22 0x0000000060026961 in target_cpu_loop (env=0x8605a7098)
    at /usr/local/poudriere/ports/default/emulators/qemu-user-static/work/qemu-bsd-user-1df9b2f/bsd-user/arm/target_arch_cpu.h:61
#23 0x00000000600268e9 in cpu_loop (env=0x18ad8)
```

**Comment by kevans91** [comment]
The fix for this hit the ports tree in r517350.
